# 130x50
Output nekot.mp4

Require echo

Set Shell "zsh"
Set Theme "ayu"
Set Height 1600
Set Width 2000
Set Framerate 30
Set FontSize 24
Set TypingSpeed 70ms
Set Margin 15
Set MarginFill "#2c2d2e"
Set BorderRadius 15
Set Padding 5

Hide
Type "./nekot -p openrouter"
Enter

Show

Sleep 3s

Type "3"
Sleep 1s

Type "m"
Sleep 1s

Type "/"
Sleep 1s

Type "qwenvl8"
Sleep 1s

Enter
Sleep 1s

Enter
Sleep 1s

Type "1"
Sleep 1s

Type "i"
Sleep 1s

Type "print the code from the image and briefly explain it"
Sleep 0.5s
Ctrl+a
Sleep 0.5s
Type "j"
Sleep 0.2s
Type "j"
Sleep 0.2s
Enter
Sleep 0.5s

Escape
Sleep 1s
Enter

Sleep 9s

Escape
Type "2"
Sleep 1s

Space
Sleep 1s

Type "kkkk"
Sleep 0.5s

Space
Sleep 0.5s

Type "3j"
Sleep 0.5s
Type "9j"
Sleep 1s

Type "y"
Sleep 3s

Escape
Sleep 2s

Ctrl+n
Sleep 2s
